magic-api:
  web: /magic/web # UI请求的界面以及UI服务地址

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.160:3306/zjdgl
    username: root
    password: GisqNyncYfyb


mybatis:
  type-aliases-package: com.example.learn.learn.domain
  mapper-locations: classpath:/mapper/*.xml



com:
  learn:
    entitys:
      importbatchesproperty:
        acessFileBasicPath: D:\zs\file\
        tableNames: nh,nhhncy,nhtz,nmfw,nmfwly,qytz,shyqr,suyqr,zjdly,zjdzdxx

